name: Go CI

on:
  push:
    branches:
      -main
      -dev
  pull_request:
    branches: 
      -main
      -dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'  

    - name: Tidy modules
      run: go mod tidy

    - name: Build
      run: go build ./...

    - name: Run tests
      run: go test -v -race ./...
      
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.55.2
      
    - name: Run golangci-lint
      run: golangci-lint run ./...
